### ISSUE TITLE
Search Knowledge Base

### ISSUE THREAD

**Issue by jonathanhickford** [ebiwd/Core-Competency-viewer#2]
As an end user
I want to be able to search the list of training resources
So that I can find resources relevant to my interests

**A/C**
 - [ ] I can search for text in the name and domain of the training resources
 - [x] Search is case insensitive
 - [x] Search will search within words
 - [x] I can clear my search results and reset to see the full list

**Comment by josephrossetto** [comment]
http://www.ebi.ac.uk/about/events/ provides an (potentially reusable) example for a Search/Filter pattern.
