### ISSUE TITLE
Reduce EBI look

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/Core-Competency-viewer#25]
Remove vis framework black bar and EBI footer.

This is a good test case for [EBI Visual Framework v1.3](https://github.com/ebiwd/EBI-Framework/issues/103).

**Comment by ebiwd-jros** [comment]
We can look at http://bioexcel.eu and see if we can set a similar colour theme and look and feel. Vera and Cath have been involved in BioExcel, so might know if there is a template/visual look and feel guide, or have contact details for the developers.

Then we can talk to Ken about how best to 'theme' the EBI framework v.1.3
