### ISSUE TITLE
Filter/facet training resources 

### ISSUE THREAD

**Issue by jonathanhickford** [ebiwd/Core-Competency-viewer#3]
As an end user
I want to be able to filter the training resource list by key attributes
So that I can reduce the number of training resources shown and find suitable ones for my needs

**A/C**
 - [x] I can filter by course type: face to face/online
 - [x] I can filter by domain from a list of domains within the knowledge base
 - [x] If I am using these filters then free text search works within the subset of free text search results
 - [x] I can reset the filters

**Comment by josephrossetto** [comment]
http://www.ebi.ac.uk/about/events/ provides an (potentially reusable) example for a Search/Filter pattern.

**Comment by khawkins98** [comment]
I'm _guessing_ that the list of domains to select from should be dynamically generated? 

That is: Should the API tell the client what the options are, or should the client generate the options on the fly based on the API's response?

**Comment by jonathanhickford** [comment]
I guess it would be more performant for the API to tell the client
