### ISSUE TITLE
Add CORS for gh-pages site

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/Core-Competency-viewer#30]
Adding a CORS policy on the Drupal Pantheon site will allow users to use the knowledge base.

Right now at https://ebiwd.github.io/Core-Competency-viewer/drupal-angularJS/:

![image](https://user-images.githubusercontent.com/928100/29276791-a3b611e6-8107-11e7-96f8-a5d88835c5c7.png)

CORS policies are now part of D8 core and can be set in: `default.services.yml`

See: https://www.drupal.org/node/2715637

**Comment by josephrossetto** [comment]
Temporary fix by following Pantheon guidelines:
https://pantheon.io/docs/services-yml/

https://ebiwd.github.io/Core-Competency-viewer/core-competency/
