### ISSUE TITLE
Define API response for knowledge base

### ISSUE THREAD

**Issue by jonathanhickford** [ebiwd/Core-Competency-viewer#7]
As a technical project team member
I want to have a defined API for retrieving the information about a given knowledge base
So that I can render the knowledge base page

**A/C**
 - [ ] API publicly defined and documented _(?Open API)_
 - [ ] Versioning strategy defined so we can make future iterations

**Comment by ebiwd-jros** [comment]
In progress:
https://app.swaggerhub.com/api/josephrossetto/ebi_training_knowledge_framework/0.0.1
